Fix OpenBSD sqlports parser
Upstream has removed [1] MASTER_SITES[0-9] columns which are required
to constuct download file names, and has also managed to break the
main database view completely:

    % sqlite3 sqlports 'select * from Ports'
    Error: in prepare, no such column: '

Switch from using the named view to custom query which reproduces
(part of) it.

[1] https://github.com/openbsd/ports/commit/b6f7e252011e832134ed8ffb7d7f210102327b96